chore: lint

diff --git a/.github/workflows/auto-merge-dependabot.yml b/.github/workflows/auto-merge-dependabot.yml
--- a/.github/workflows/auto-merge-dependabot.yml
+++ b/.github/workflows/auto-merge-dependabot.yml
@@ -1,9 +1,7 @@
 name: Dependabot fetch metadata
 on: pull_request
-
 permissions:
   pull-requests: write
-
 jobs:
   dependabot:
     runs-on: ubuntu-latest
@@ -14,17 +12,35 @@ jobs:
         uses: dependabot/fetch-metadata@v2
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Add a label for the update type
         run: gh pr edit "$PR_URL" --add-label "${{ steps.metadata.outputs.update-type }}"
         env:
           PR_URL: ${{github.event.pull_request.html_url}}
-      - name: Enable auto-merge
-        # Reminder to the audience: The auto-merge won't trigger until the PR is approved.
-        run: gh pr edit "$PR_URL" --enable-auto-merge
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Add dependency type label
+        run: gh pr edit "$PR_URL" --add-label "dependency:${{ steps.metadata.outputs.dependency-type }}"
         env:
           PR_URL: ${{github.event.pull_request.html_url}}
-      - name: Approve and merge if patch update
-        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Enable auto-merge
+        run: gh pr edit "$PR_URL" --enable-auto-merge || echo "Unable to enable auto-merge, continuing workflow"
+        env:
+          PR_URL: ${{github.event.pull_request.html_url}}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Approve and merge if patch update or security update
+        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.security-vuln-alerts > 0
         run: gh pr review --approve "$PR_URL"
         env:
           PR_URL: ${{github.event.pull_request.html_url}}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Notify team of major/minor updates
+        if: steps.metadata.outputs.update-type != 'version-update:semver-patch' && steps.metadata.outputs.security-vuln-alerts == 0
+        run: gh pr comment "$PR_URL" --body "This PR contains a non-patch update. Please review carefully before approving."
+        env:
+          PR_URL: ${{github.event.pull_request.html_url}}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
